include(FindPackageHandleStandardArgs)
set(SURFACE_SEARCH_PATHS /usr/local/SURFACE/ /usr/SURFACE/ ${SURFACE_PATH})

find_path(
  SURFACE_INCLUDE_DIR *.hh
  HINTS $ENV{SURFACE_DIR}
  PATH_SUFFIXES include
  PATHS ${SURFACE_SEARCH_PATHS})

find_library(
  SURFACE_LIB
  NAMES libSurface.a
  HINTS $ENV{SURFACE_DIR}
  PATH_SUFFIXES lib
  PATHS ${SURFACE_SEARCH_PATHS})

find_package_handle_standard_args(SURFACE REQUIRED_VARS SURFACE_LIB)

set(SURFACE_INCLUDE_DIRS ${SURFACE_INCLUDE_DIR})
set(SURFACE_LIBS ${SURFACE_LIB})
mark_as_advanced(SURFACE_INCLUDE_DIR SURFACE_LIB)
